---
# Type

- name: 'Type: Addition/Enhancement'
  color: 7fdeea
  description: 'New features for the docs.'
- name: 'Type: Typo'
  color: f8bad0
  description: 'Misspellings, grammar fixes and other simple corrections to the docs.'
- name: 'Type: Unclear/Inaccurate'
  color: eb3f79
  description: 'Fixing docs that are incorrect, misleading or confusing.'
- name: 'Type: Formatting/Accessibility'
  color: ac1357
  description: 'Improving presentation and a11y of the docs.'
- name: 'Type: Build Process'
  color: 7985cb
  description: 'Docusaurus, GitHub Actions and other tools used to create the docs.'

# Status

- name: 'Status: Available'
  color: bee4be
  description: 'Not currently being worked on. Take the lead!'
- name: 'Status: In Progress'
  color: fef2c0
  description: 'Work is underway.'
- name: 'Status: Update Needed'
  color: e11d21
  description: 'Missing necessary information or review.'
- name: 'Status: Blocked or Postponed'
  color: 006a74
  description: 'On hold.'
- name: 'Status: Done'
  color: 000000
  description: 'Completed.'
- name: "Status: Won't Fix"
  color: cdcdcd
  description:
    'Outside project scope, off-topic, spam, or otherwise does not apply to this
    project.'

# Welcome

- name: 'good first issue'
  color: 2da44e
  description:
    'Beginner-friendly issue for people wanting to contribute to this project.'
- name: 'help wanted'
  color: 2da44e
  description:
    'We need some extra helping hands or expertise in order to resolve this!'
