name: Documentation change
description: Suggest a change to Premail documentation
body:
  - type: checkboxes
    id: change_type
    attributes:
      label: Type of change (check all that apply)
      options:
        - label: Addition/enhancement
        - label: Typos
        - label: Inaccurate, unclear or confusing wording
        - label: Formatting or accessibility
        - label: Build process (Docusaurus, GitHub Actions, etc.)
        - label: Other (please describe below)
    validations:
      required: true
  - type: textarea
    id: pages
    attributes:
      label: URLs or links to the pages on Premail.dev
  - type: textarea
    id: description
    attributes:
      label: Describe the change
      description:
        Summarize your suggested changes below, or open a Pull Request and include a link to it here.
    validations:
      required: true
