name: Alex inclusive writing check
# https://alexjs.com

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  alex:
    name: Check for inclusive writing
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Run Alexjs
        uses: theashraf/alex-action@master
