name: Create <mjml-bullet-list> issue on change

on:
  push:
    branches: [main]
    paths:
      - docs/02-components/02-bullet-list.md

jobs:
  create_issue:
    name: Create an issue on push
    runs-on: ubuntu-latest
    steps:
      - name: Get today's date
        id: date
        run: |
          echo "::set-output name=today::$(date "+%b %d, %Y")"
      - name: Create an issue
        uses: actions-ecosystem/action-create-issue@v1
        with:
          repo: premail/mjml-bullet-list
          assignees: rootwork
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          title: Component documentation update ${{ steps.date.outputs.today }}
          body: |
            Documentation for `<mjml-bullet-list>` has been updated at [premail/website](https://github.com/premail/website/commits/main/docs/02-components/02-bullet-list.md)

            The [README.md](https://github.com/premail/mjml-bullet-list/blob/main/README.md) file needs to be updated to match.

          labels: |
            'Type: Documentation'
