name: On changes to basic documentation, copy to code repo

on:
  push:
    branches: [main]
    paths:
      - src/pages/**.md

jobs:
  copy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Copy files
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'src/pages/**.md'
          destination-username: 'premail'
          destination-repository: 'premail'
          destination-branch: 'v2.0.0'
          destination-directory: 'docs'
          commit-email: 'git@premail.dev'
