name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  build:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: Premail
          user_email: git@premail.dev
  copy:
    needs: build
    name: Copy basic documentation files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run:
          export GITHUB_USER=rootwork
          export GITHUB_EMAIL=git@rootwork.org
          export FROM_REPO=website
          export FROM_PATH=src/pages/*.md
          export TO_REPO=premail
          export TO_BRANCH=v2.0.0
          export TO_PATH=docs
          git config --global user.email $GITHUB_EMAIL
          git config --global user.name $GITHUB_USER
          git clone https://github.com/premail/$FROM_REPO.git
          git clone https://github.com/premail/$TO_REPO.git
          cd $TO_REPO
          git checkout $TO_BRANCH
      - name: Copy files
        run: |
          cp ../$FROM_REPO/$FROM_PATH $TO_PATH
          git update-index -q --refresh
      - name: Commit any changes
        with:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          if ! git diff-index --quiet HEAD --; then
            git remote set-url origin https://$GITHUB_USER:$API_TOKEN_GITHUB@github.com/premail/$TO_REPO
            git add .
            git commit -m "Updated documentation files from premail/$FROM_REPO" --signoff
            git push
          fi
