name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  build:
    name: Build and deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: Premail
          user_email: git@premail.dev
  copy:
    needs: build
    name: Copy basic documentation files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          path: ./website
      - name: Checkout code repo
        uses: actions/checkout@master
        with:
          repository: premail/premail
          token: ${{ secrets.API_TOKEN_GITHUB }}
          path: ./premail
      - name: Copy files
          run: |
            FILES=./website/src/pages/*.md
            for f in $FILES; do
              echo "Copying $f"
              cp -R $f ./premail
            done
      - name: Commit changes
          run: |
            cd ./premail
            git add .
            git config user.name rootwork
            git config user.email git@rootwork.org
            git commit -am "Updated documentation files"
            git push
