name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_DEPLOY }}
      - name: Build website
        run: |
          yarn install --frozen-lockfile
          yarn build
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GH_PAGES_DEPLOY }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # Assign commit authorship to the official GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: Premail
          user_email: git@premail.dev
      - name: Copy basic documentation files
        uses: nkoppel/push-files-to-another-repository@latest
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'src/pages/**.md'
          destination-username: 'premail'
          destination-repository: 'premail'
          destination-branch: 'v2.0.0'
          destination-directory: 'docs'
          commit-email: 'git@premail.dev'
